Add script to clone and flash an SD card

diff --git a/,sdcard-flash b/,sdcard-flash
--- a/,sdcard-flash
+++ b/,sdcard-flash
@@ -59,9 +59,13 @@ fi
 # UNMOUNT DEVICE #
 ##################
 
-if ! grep "${DEVICE}" /proc/mounts | cut -d' ' -f1 | xargs -r umount ; then
-    echo "Could not unmount device ${DEVICE} partitions, aborting"
-    exit 1
+MOUNTS="$(grep "${DEVICE}" /proc/mounts || true)"
+
+if [[ -n "${MOUNTS}" ]] ; then
+    if ! echo "${MOUNTS}" | cut -d' ' -f1 | xargs -r umount ; then
+        echo "Could not unmount device ${DEVICE} partitions, aborting"
+        exit 1
+    fi
 fi
 
 #################
